# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pickle_ <- function(object) {
    .Call(`_pickleR_pickle_`, object)
}

unpickle_ <- function(pickleDefinition) {
    .Call(`_pickleR_unpickle_`, pickleDefinition)
}

